/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CollegeId = string;
export interface CollegeRecord {
  'id' : CollegeId,
  'courses' : Array<CourseRecord>,
  'annualFees' : bigint,
  'placementPercent' : bigint,
  'name' : string,
  'totalStudents' : bigint,
  'description' : string,
  'avgPackageLPA' : number,
  'accreditation' : string,
  'topRecruiters' : Array<string>,
  'establishedYear' : bigint,
  'state' : string,
  'rating' : number,
  'location' : string,
  'cutoffs' : Array<CutoffRecord>,
}
export interface CourseRecord {
  'durationYears' : bigint,
  'name' : string,
  'seats' : bigint,
}
export interface CutoffRecord {
  'rank' : bigint,
  'category' : string,
  'examType' : string,
}
export interface PredictorQuery { 'rank' : bigint, 'examType' : string }
export interface SearchFilter {
  'minFees' : [] | [bigint],
  'page' : bigint,
  'pageSize' : bigint,
  'nameQuery' : [] | [string],
  'maxFees' : [] | [bigint],
  'location' : [] | [string],
}
export interface SearchResult {
  'totalCount' : bigint,
  'colleges' : Array<CollegeRecord>,
}
export interface _SERVICE {
  'getAllLocations' : ActorMethod<[], Array<string>>,
  'getCollege' : ActorMethod<[CollegeId], [] | [CollegeRecord]>,
  'getColleges' : ActorMethod<[SearchFilter], SearchResult>,
  'getCollegesById' : ActorMethod<[Array<CollegeId>], Array<CollegeRecord>>,
  'initializeData' : ActorMethod<[], undefined>,
  'predictColleges' : ActorMethod<[PredictorQuery], Array<CollegeRecord>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];