/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CollegeId = IDL.Text;
export const CourseRecord = IDL.Record({
  'durationYears' : IDL.Nat,
  'name' : IDL.Text,
  'seats' : IDL.Nat,
});
export const CutoffRecord = IDL.Record({
  'rank' : IDL.Nat,
  'category' : IDL.Text,
  'examType' : IDL.Text,
});
export const CollegeRecord = IDL.Record({
  'id' : CollegeId,
  'courses' : IDL.Vec(CourseRecord),
  'annualFees' : IDL.Nat,
  'placementPercent' : IDL.Nat,
  'name' : IDL.Text,
  'totalStudents' : IDL.Nat,
  'description' : IDL.Text,
  'avgPackageLPA' : IDL.Float64,
  'accreditation' : IDL.Text,
  'topRecruiters' : IDL.Vec(IDL.Text),
  'establishedYear' : IDL.Nat,
  'state' : IDL.Text,
  'rating' : IDL.Float64,
  'location' : IDL.Text,
  'cutoffs' : IDL.Vec(CutoffRecord),
});
export const SearchFilter = IDL.Record({
  'minFees' : IDL.Opt(IDL.Nat),
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'nameQuery' : IDL.Opt(IDL.Text),
  'maxFees' : IDL.Opt(IDL.Nat),
  'location' : IDL.Opt(IDL.Text),
});
export const SearchResult = IDL.Record({
  'totalCount' : IDL.Nat,
  'colleges' : IDL.Vec(CollegeRecord),
});
export const PredictorQuery = IDL.Record({
  'rank' : IDL.Nat,
  'examType' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllLocations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCollege' : IDL.Func([CollegeId], [IDL.Opt(CollegeRecord)], ['query']),
  'getColleges' : IDL.Func([SearchFilter], [SearchResult], ['query']),
  'getCollegesById' : IDL.Func(
      [IDL.Vec(CollegeId)],
      [IDL.Vec(CollegeRecord)],
      ['query'],
    ),
  'initializeData' : IDL.Func([], [], []),
  'predictColleges' : IDL.Func(
      [PredictorQuery],
      [IDL.Vec(CollegeRecord)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CollegeId = IDL.Text;
  const CourseRecord = IDL.Record({
    'durationYears' : IDL.Nat,
    'name' : IDL.Text,
    'seats' : IDL.Nat,
  });
  const CutoffRecord = IDL.Record({
    'rank' : IDL.Nat,
    'category' : IDL.Text,
    'examType' : IDL.Text,
  });
  const CollegeRecord = IDL.Record({
    'id' : CollegeId,
    'courses' : IDL.Vec(CourseRecord),
    'annualFees' : IDL.Nat,
    'placementPercent' : IDL.Nat,
    'name' : IDL.Text,
    'totalStudents' : IDL.Nat,
    'description' : IDL.Text,
    'avgPackageLPA' : IDL.Float64,
    'accreditation' : IDL.Text,
    'topRecruiters' : IDL.Vec(IDL.Text),
    'establishedYear' : IDL.Nat,
    'state' : IDL.Text,
    'rating' : IDL.Float64,
    'location' : IDL.Text,
    'cutoffs' : IDL.Vec(CutoffRecord),
  });
  const SearchFilter = IDL.Record({
    'minFees' : IDL.Opt(IDL.Nat),
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'nameQuery' : IDL.Opt(IDL.Text),
    'maxFees' : IDL.Opt(IDL.Nat),
    'location' : IDL.Opt(IDL.Text),
  });
  const SearchResult = IDL.Record({
    'totalCount' : IDL.Nat,
    'colleges' : IDL.Vec(CollegeRecord),
  });
  const PredictorQuery = IDL.Record({
    'rank' : IDL.Nat,
    'examType' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllLocations' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCollege' : IDL.Func([CollegeId], [IDL.Opt(CollegeRecord)], ['query']),
    'getColleges' : IDL.Func([SearchFilter], [SearchResult], ['query']),
    'getCollegesById' : IDL.Func(
        [IDL.Vec(CollegeId)],
        [IDL.Vec(CollegeRecord)],
        ['query'],
      ),
    'initializeData' : IDL.Func([], [], []),
    'predictColleges' : IDL.Func(
        [PredictorQuery],
        [IDL.Vec(CollegeRecord)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };